// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4QdGUxYZ768Wecu7CZ2yaQ2vmURvWcZI',
    appId: '1:165868264967:web:8bed8deba3ab1adf8154a2',
    messagingSenderId: '165868264967',
    projectId: 'rejoice-3bf02',
    authDomain: 'rejoice-3bf02.firebaseapp.com',
    storageBucket: 'rejoice-3bf02.firebasestorage.app',
    measurementId: 'G-4SLEG84ELM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA23BIa1hJZsy0b8pLcLTZDsmllwdFQDaI',
    appId: '1:165868264967:android:4066dce69dc1aa198154a2',
    messagingSenderId: '165868264967',
    projectId: 'rejoice-3bf02',
    storageBucket: 'rejoice-3bf02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOxvLcQQBBHUQ8R18emHYc1NcUzF9Y75U',
    appId: '1:165868264967:ios:d72eb82ec8743d518154a2',
    messagingSenderId: '165868264967',
    projectId: 'rejoice-3bf02',
    storageBucket: 'rejoice-3bf02.firebasestorage.app',
    iosBundleId: 'com.example.efraho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOxvLcQQBBHUQ8R18emHYc1NcUzF9Y75U',
    appId: '1:165868264967:ios:d72eb82ec8743d518154a2',
    messagingSenderId: '165868264967',
    projectId: 'rejoice-3bf02',
    storageBucket: 'rejoice-3bf02.firebasestorage.app',
    iosBundleId: 'com.example.efraho',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4QdGUxYZ768Wecu7CZ2yaQ2vmURvWcZI',
    appId: '1:165868264967:web:d4d0bb4a1b83f46a8154a2',
    messagingSenderId: '165868264967',
    projectId: 'rejoice-3bf02',
    authDomain: 'rejoice-3bf02.firebaseapp.com',
    storageBucket: 'rejoice-3bf02.firebasestorage.app',
    measurementId: 'G-DDGC6SCMXP',
  );
}
